# Generated by Django 4.1.5 on 2023-01-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_image', models.CharField(max_length=1000)),
                ('about_me', models.CharField(max_length=1000)),
                ('favorite', models.CharField(max_length=1000)),
                ('wish_list', models.CharField(max_length=1000)),
                ('my_wines_list', models.CharField(max_length=1000)),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=100)),
                ('year_produced', models.CharField(max_length=50)),
                ('wine_picture', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('wine_type', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('favorite', models.BooleanField(default=False)),
                ('wish_list', models.BooleanField(default=False)),
                ('wine_list', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineadventureapi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winery_name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineadventureapi.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineadventureapi.country')),
            ],
        ),
        migrations.CreateModel(
            name='Wine_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineadventureapi.category')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineadventureapi.wine')),
            ],
        ),
        migrations.CreateModel(
            name='Wine101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=50)),
                ('context', models.CharField(max_length=100)),
                ('article_image', models.CharField(max_length=100)),
                ('article_link', models.CharField(max_length=150)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineadventureapi.profile')),
            ],
        ),
        migrations.AddField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineadventureapi.winery'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineadventureapi.user'),
        ),
    ]
