# Generated by Django 4.1.5 on 2023-01-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineadventureapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='winery',
        ),
        migrations.AlterField(
            model_name='wine_category',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winecat', to='wineadventureapi.wine'),
        ),
        migrations.DeleteModel(
            name='Winery',
        ),
    ]
